import{i as n,S as u}from"./assets/vendor-BrddEoy-.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const p="https://pixabay.com/api/",g="33694347-6ae8de5621b95f7febdf77706",m=a=>fetch(`${p}?key=${g}&q=${a}&image_type=photo&orientation=horizontal&safesearch=true`).then(r=>{if(!r.ok)throw new Error(r.message);return r.json()}),f=({largeImageURL:a,webformatURL:r,tags:s,likes:i,views:e,comments:t,downloads:l})=>`<li class="gallery-item">
  <a href="${a}" class="gallery-link">
  <img class="gallery-image" src="${r}" alt="${s}"/>
  </a>
  <ul class="gallery-interactions-block">
  <li class="gallery-interactions-item"><span class="gallery-interactions-activity">Likes</span><span class="gallery-activity-quantity">${i}</span></li>
  <li class="gallery-interactions-item"><span class="gallery-interactions-activity">Views</span><span class="gallery-activity-quantity">${e}</span></li>
  <li class="gallery-interactions-item"><span class="gallery-interactions-activity">Comments</span><span class="gallery-activity-quantity">${t}</span></li>
  <li class="gallery-interactions-item"><span class="gallery-interactions-activity">Downloads</span><span class="gallery-activity-quantity">${l}</span></li>
  </ul>
  </li>`,y=document.querySelector("#js-form"),d=document.querySelector("#js-input"),o=document.querySelector("#js-gallery"),c=document.querySelector(".loader");y.addEventListener("submit",h);function h(a){a.preventDefault();const r=d.value.trim();o.innerHTML="",c.classList.add("block"),m(r).then(({hits:s})=>{if(s.length===0)return n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});const i=new u(".gallery a",{captionDelay:250,captionsData:"alt"});o.innerHTML=s.map(f).join(""),i.refresh()}).catch(()=>n.error({title:"Error",message:"An error occurred while fetching the images. Please try again later!",position:"topRight"})).finally(()=>{c.classList.remove("block"),y.reset()})}
//# sourceMappingURL=index.js.map
